version: '3.7'

services:
    mysql-development:
        image: mysql:8.0.21
        environment:
            MYSQL_ROOT_PASSWORD: khunou
            MYSQL_DATABASE: projet_7
        ports:
            - "3308:3306"
        volumes:
            - proj-mysql-data:/var/lib/mysql

    app: 
        build: 
            context: ./front-end
            dockerfile: Dockerfile
        ports: 
            - 3000:3000
        stdin_open: true

    server: 
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports: 
            - 5000:5000
        stdin_open: true

volumes: 
    proj-mysql-data: